[package]
name = "agentos-channels"
version.workspace = true
edition.workspace = true

[dependencies]
agentos-types = { path = "../agentos-types" }
agentos-http = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }
subtle = "2"
base64 = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
futures-util = "0.3"
urlencoding = "2"
url = { workspace = true }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
lettre = { workspace = true }
