use crate::kernel::Kernel;
use std::path::Path;

impl Kernel {
    pub(crate) const CORE_MANIFESTS: &[(&'static str, &'static str)] = &[
        (
            "file-reader.toml",
            include_str!("../../../tools/core/file-reader.toml"),
        ),
        (
            "file-writer.toml",
            include_str!("../../../tools/core/file-writer.toml"),
        ),
        (
            "memory-search.toml",
            include_str!("../../../tools/core/memory-search.toml"),
        ),
        (
            "memory-write.toml",
            include_str!("../../../tools/core/memory-write.toml"),
        ),
        (
            "data-parser.toml",
            include_str!("../../../tools/core/data-parser.toml"),
        ),
        (
            "agent-list.toml",
            include_str!("../../../tools/core/agent-list.toml"),
        ),
        (
            "agent-manual.toml",
            include_str!("../../../tools/core/agent-manual.toml"),
        ),
        (
            "agent-message.toml",
            include_str!("../../../tools/core/agent-message.toml"),
        ),
        (
            "agent-self.toml",
            include_str!("../../../tools/core/agent-self.toml"),
        ),
        (
            "archival-insert.toml",
            include_str!("../../../tools/core/archival-insert.toml"),
        ),
        (
            "archival-search.toml",
            include_str!("../../../tools/core/archival-search.toml"),
        ),
        (
            "datetime.toml",
            include_str!("../../../tools/core/datetime.toml"),
        ),
        (
            "episodic-list.toml",
            include_str!("../../../tools/core/episodic-list.toml"),
        ),
        (
            "escalation-status.toml",
            include_str!("../../../tools/core/escalation-status.toml"),
        ),
        (
            "file-delete.toml",
            include_str!("../../../tools/core/file-delete.toml"),
        ),
        (
            "file-diff.toml",
            include_str!("../../../tools/core/file-diff.toml"),
        ),
        (
            "file-editor.toml",
            include_str!("../../../tools/core/file-editor.toml"),
        ),
        (
            "file-glob.toml",
            include_str!("../../../tools/core/file-glob.toml"),
        ),
        (
            "file-grep.toml",
            include_str!("../../../tools/core/file-grep.toml"),
        ),
        (
            "file-move.toml",
            include_str!("../../../tools/core/file-move.toml"),
        ),
        (
            "hardware-info.toml",
            include_str!("../../../tools/core/hardware-info.toml"),
        ),
        (
            "http-client.toml",
            include_str!("../../../tools/core/http-client.toml"),
        ),
        (
            "log-reader.toml",
            include_str!("../../../tools/core/log-reader.toml"),
        ),
        (
            "memory-block-delete.toml",
            include_str!("../../../tools/core/memory-block-delete.toml"),
        ),
        (
            "memory-block-list.toml",
            include_str!("../../../tools/core/memory-block-list.toml"),
        ),
        (
            "memory-block-read.toml",
            include_str!("../../../tools/core/memory-block-read.toml"),
        ),
        (
            "memory-block-write.toml",
            include_str!("../../../tools/core/memory-block-write.toml"),
        ),
        (
            "memory-delete.toml",
            include_str!("../../../tools/core/memory-delete.toml"),
        ),
        (
            "memory-read.toml",
            include_str!("../../../tools/core/memory-read.toml"),
        ),
        (
            "memory-stats.toml",
            include_str!("../../../tools/core/memory-stats.toml"),
        ),
        (
            "network-monitor.toml",
            include_str!("../../../tools/core/network-monitor.toml"),
        ),
        (
            "procedure-create.toml",
            include_str!("../../../tools/core/procedure-create.toml"),
        ),
        (
            "procedure-delete.toml",
            include_str!("../../../tools/core/procedure-delete.toml"),
        ),
        (
            "procedure-list.toml",
            include_str!("../../../tools/core/procedure-list.toml"),
        ),
        (
            "procedure-search.toml",
            include_str!("../../../tools/core/procedure-search.toml"),
        ),
        (
            "process-manager.toml",
            include_str!("../../../tools/core/process-manager.toml"),
        ),
        (
            "shell-exec.toml",
            include_str!("../../../tools/core/shell-exec.toml"),
        ),
        (
            "task-delegate.toml",
            include_str!("../../../tools/core/task-delegate.toml"),
        ),
        (
            "task-list.toml",
            include_str!("../../../tools/core/task-list.toml"),
        ),
        (
            "task-status.toml",
            include_str!("../../../tools/core/task-status.toml"),
        ),
        ("think.toml", include_str!("../../../tools/core/think.toml")),
        (
            "web-fetch.toml",
            include_str!("../../../tools/core/web-fetch.toml"),
        ),
    ];

    /// Install bundled core tool manifests into the runtime directory if not already present.
    pub(crate) fn install_core_manifests(core_dir: &Path) -> Result<(), anyhow::Error> {
        for (filename, content) in Self::CORE_MANIFESTS {
            let dest = core_dir.join(filename);
            if !dest.exists()
                || std::fs::metadata(&dest)
                    .map(|m| m.len() == 0)
                    .unwrap_or(false)
            {
                std::fs::write(&dest, content)?;
            }
        }
        Ok(())
    }
}
