pub mod adapters;
pub mod agent_message_bus;
pub mod agent_registry;
pub mod background_pool;
pub mod commands;
pub mod config;
pub mod consolidation;
pub mod context;
pub mod context_compiler;
pub mod context_injector;
pub mod context_memory_store;
pub mod core_manifests;
pub mod cost_tracker;
pub mod escalation;
pub mod event_bus;
pub mod event_dispatch;
pub mod health;
pub mod health_monitor;
pub mod identity;
pub mod inbound_router;
pub mod injection_scanner;
pub mod intent_validator;
pub mod kernel;
pub mod kernel_action;
pub mod logging;
pub mod memory_blocks;
pub mod memory_extraction;
pub mod metrics;
pub mod network_safety;
pub mod notification_router;
pub mod otel_exporter;
pub mod rate_limit;
pub mod resource_arbiter;
pub mod retrieval_gate;
pub mod risk_classifier;
pub mod router;
pub mod rpc_manager;
pub mod run_loop;
pub mod schedule_manager;
pub mod scheduler;
pub mod schema_registry;
pub(crate) mod sd_notify;
pub mod snapshot;
pub mod state_store;
pub mod task_completion;
pub mod task_executor;
pub(crate) mod task_summary;
pub mod task_trace;
pub mod tool_call;
pub mod tool_registry;
pub mod trace_collector;
pub mod trigger_prompt;
pub mod user_channel_registry;
pub mod user_inbox;

pub use agent_message_bus::AgentMessageBus;
pub use agent_registry::AgentRegistry;
pub use config::{load_config, KernelConfig};
pub use context::ContextManager;
pub use context_compiler::ContextCompiler;
pub use kernel::{resolve_boot_vault_passphrase, Kernel};
pub use otel_exporter::OtelExporter;
pub use retrieval_gate::{
    IndexType, RetrievalExecutor, RetrievalGate, RetrievalOutcome, RetrievalPlan, RetrievalResult,
};
pub use scheduler::TaskScheduler;
pub use tool_call::{parse_intent_type, ParsedToolCall, ToolCallRequest};
pub use tool_registry::ToolRegistry;
