"""
Wrapper script generator for AgentOS Python SDK tools.

Called by ``agentos tool install <file.py>`` to produce a wrapper script in
``$data_dir/scripts/``.  The wrapper:

1. Carries all annotation headers ScriptParser expects (``@agentos tool:``,
   ``@schema:``, etc.).
2. Imports the decorated function from the original source file.
3. Calls ``<fn>.run()`` as the entry point.

The ScriptWatcher picks up the wrapper automatically when it lands in the
scripts directory — no kernel restart required.

Usage:
    from agentos.generator import write_wrapper

    manifest = my_tool._agentos_manifest
    wrapper_path = write_wrapper(manifest, source_path="/path/to/my_tool.py",
                                 scripts_dir="/tmp/agentos/data/scripts")
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


def generate_wrapper(manifest: dict[str, Any], source_path: str | Path) -> str:
    """
    Generate the content of a wrapper script for the given tool manifest.

    Args:
        manifest:    The dict produced by ``fn._agentos_manifest``.
        source_path: Absolute path to the original ``.py`` source file.

    Returns:
        A string containing the complete wrapper script content, ready to
        be written to ``<scripts_dir>/<name>.py``.
    """
    source_path = Path(source_path).resolve()
    source_dir = str(source_path.parent)

    name = manifest["name"]
    fn_name = manifest.get("fn_name", name.replace("-", "_"))
    description = manifest.get("description", "")
    version = manifest.get("version", "0.1.0")
    permissions = manifest.get("permissions", [])
    input_schema = manifest.get("input_schema", {"type": "object", "properties": {}})

    # Compact single-line JSON for the @schema: annotation
    schema_json = json.dumps(input_schema, separators=(",", ":"))

    # Build permissions string — fall back to read-only if none declared
    perms_str = ", ".join(permissions) if permissions else "fs.data:r"

    # Escape the source directory path for embedding in a Python string literal
    source_dir_repr = json.dumps(source_dir)  # double-quoted, safely escaped

    lines = [
        "#!/usr/bin/env python3",
        f"# @agentos tool: {name}",
        f"# @description: {description}",
        f"# @version: {version}",
        f"# @permissions: {perms_str}",
        f"# @schema: {schema_json}",
        "# Generated by `agentos tool install` — do not edit manually.",
        "import asyncio, json, os, sys",
        f"sys.path.insert(0, {source_dir_repr})",
        f"from {source_path.stem} import {fn_name}",
        "",
        "",
        "def _main():",
        '    payload = json.loads(os.environ.get("AGENTOS_INPUT", "{}"))',
        f"    result = asyncio.run({fn_name}(**payload))",
        "    print(json.dumps(result))",
        "",
        "",
        'if __name__ == "__main__":',
        "    _main()",
    ]

    return "\n".join(lines) + "\n"


def write_wrapper(
    manifest: dict[str, Any],
    source_path: str | Path,
    scripts_dir: str | Path,
) -> Path:
    """
    Write a wrapper script to ``scripts_dir/<name>.py`` and make it executable.

    Creates ``scripts_dir`` if it does not exist.

    Returns:
        The ``Path`` to the generated wrapper file.
    """
    name = manifest["name"]
    scripts_dir = Path(scripts_dir)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    wrapper_path = scripts_dir / f"{name}.py"
    content = generate_wrapper(manifest, source_path)
    wrapper_path.write_text(content, encoding="utf-8")

    # Make the wrapper executable (rwxr-xr-x)
    current_mode = wrapper_path.stat().st_mode
    wrapper_path.chmod(current_mode | 0o755)

    return wrapper_path
