use crate::traits::{AgentTool, ToolExecutionContext};
use agentos_memory::{ProceduralStore, Procedure, ProcedureStep};
use agentos_types::{AgentOSError, PermissionOp};
use async_trait::async_trait;
use std::sync::Arc;

pub struct ProcedureCreate {
    procedural: Arc<ProceduralStore>,
}

impl ProcedureCreate {
    pub fn new(procedural: Arc<ProceduralStore>) -> Self {
        Self { procedural }
    }
}

#[async_trait]
impl AgentTool for ProcedureCreate {
    fn name(&self) -> &str {
        "procedure-create"
    }

    fn required_permissions(&self) -> Vec<(String, PermissionOp)> {
        vec![("memory.procedural".to_string(), PermissionOp::Write)]
    }

    async fn execute(
        &self,
        payload: serde_json::Value,
        context: ToolExecutionContext,
    ) -> Result<serde_json::Value, AgentOSError> {
        if !context
            .permissions
            .check("memory.procedural", PermissionOp::Write)
        {
            return Err(AgentOSError::PermissionDenied {
                resource: "memory.procedural".to_string(),
                operation: format!("{:?}", PermissionOp::Write),
            });
        }

        let name = payload
            .get("name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                AgentOSError::SchemaValidation("procedure-create requires 'name' field".into())
            })?;

        let description = payload
            .get("description")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                AgentOSError::SchemaValidation(
                    "procedure-create requires 'description' field".into(),
                )
            })?;

        // Parse steps: array of {action, tool?, expected_outcome?} objects
        let steps: Vec<ProcedureStep> = match payload.get("steps") {
            Some(serde_json::Value::Array(arr)) if !arr.is_empty() => {
                let mut parsed = Vec::with_capacity(arr.len());
                for (i, step) in arr.iter().enumerate() {
                    let action = step
                        .get("action")
                        .and_then(|v| v.as_str())
                        .filter(|s| !s.is_empty())
                        .ok_or_else(|| {
                            AgentOSError::SchemaValidation(format!(
                                "step[{}] requires a non-empty 'action' field",
                                i
                            ))
                        })?;
                    parsed.push(ProcedureStep {
                        order: i,
                        action: action.to_string(),
                        tool: step
                            .get("tool")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string()),
                        expected_outcome: step
                            .get("expected_outcome")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string()),
                    });
                }
                parsed
            }
            _ => {
                return Err(AgentOSError::SchemaValidation(
                    "procedure-create requires a non-empty 'steps' array".into(),
                ))
            }
        };

        let preconditions: Vec<String> = payload
            .get("preconditions")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        let postconditions: Vec<String> = payload
            .get("postconditions")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        let tags: Vec<String> = payload
            .get("tags")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(String::from))
                    .collect()
            })
            .unwrap_or_default();

        let procedure = Procedure {
            id: String::new(), // auto-generated by store
            name: name.to_string(),
            description: description.to_string(),
            preconditions,
            steps,
            postconditions,
            success_count: 0,
            failure_count: 0,
            source_episodes: Vec::new(),
            agent_id: Some(context.agent_id),
            tags,
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
        };

        let id = self.procedural.store(&procedure).await.map_err(|e| {
            AgentOSError::ToolExecutionFailed {
                tool_name: "procedure-create".into(),
                reason: format!("Store failed: {}", e),
            }
        })?;

        Ok(serde_json::json!({
            "success": true,
            "id": id,
            "name": name,
            "message": "Procedure stored in procedural memory",
        }))
    }
}
