use crate::traits::{AgentTool, ToolExecutionContext};
use agentos_types::{AgentOSError, PermissionOp};
use async_trait::async_trait;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::time::Duration;
use tokio::process::Command;

/// Maximum permitted @timeout value (seconds). Prevents runaway scripts from
/// holding a tool slot indefinitely.
const MAX_SCRIPT_TIMEOUT_SECS: u64 = 3600;

/// Cached result of the `bwrap --version` availability check.
/// Avoids re-spawning a probe process on every script tool invocation.
static BWRAP_AVAILABLE: OnceLock<bool> = OnceLock::new();

async fn is_bwrap_available() -> bool {
    if let Some(&cached) = BWRAP_AVAILABLE.get() {
        return cached;
    }
    let available = Command::new("bwrap")
        .arg("--version")
        .output()
        .await
        .is_ok();
    // OnceLock::set may fail on a race (two concurrent first calls) — that's fine;
    // the winning value is whichever was set first, and both paths agree.
    let _ = BWRAP_AVAILABLE.set(available);
    available
}

// ---------------------------------------------------------------------------
// ScriptAnnotations
// ---------------------------------------------------------------------------

/// Parsed metadata extracted from a script file's annotation header.
#[derive(Debug, Clone)]
pub struct ScriptAnnotations {
    /// Tool name (kebab-case). From `@agentos tool:`.
    pub name: String,
    /// Human + LLM readable description.
    pub description: String,
    /// Semver version string.
    pub version: String,
    /// Raw permission strings e.g. `["fs.data:r", "network.outbound:x"]`.
    pub permissions: Vec<String>,
    /// Risk class string e.g. `"readonly_scoped"`.
    pub risk: String,
    /// Max execution seconds.
    pub timeout_secs: u64,
    /// Capability tags for semantic discoverability.
    pub tags: Vec<String>,
    /// Whether to pass `--share-net` to bwrap.
    pub allow_network: bool,
    /// Full JSON Schema from `@schema:` annotation (generated by Python SDK).
    /// When present, this schema is surfaced to the LLM instead of the
    /// free-text description alone.
    pub schema: Option<serde_json::Value>,
}

// ---------------------------------------------------------------------------
// ScriptParser
// ---------------------------------------------------------------------------

/// Parses annotation headers from script files.
///
/// Annotations are embedded in comment lines near the top of the file.
/// Supported comment prefixes: `#`, `//`, `--`.
/// The prefix is detected from the shebang line or file extension.
///
/// A file without `@agentos tool:` is silently ignored (`Ok(None)`).
pub struct ScriptParser;

impl ScriptParser {
    /// Parse a script file and return its annotations, or `None` if the file
    /// does not carry an `@agentos tool:` annotation.
    pub fn parse(path: &Path) -> Result<Option<ScriptAnnotations>, AgentOSError> {
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            // File deleted between the watcher event and the parse — not an error.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            // Binary file / non-UTF-8 — silently skip, not a script file.
            Err(e) if e.kind() == std::io::ErrorKind::InvalidData => return Ok(None),
            Err(e) => {
                return Err(AgentOSError::StorageError(format!(
                    "Failed to read script {}: {}",
                    path.display(),
                    e
                )))
            }
        };
        let prefix = Self::detect_comment_prefix(&content, path);
        Self::extract_annotations(&content, prefix)
    }

    fn detect_comment_prefix(content: &str, path: &Path) -> &'static str {
        if let Some(first_line) = content.lines().next() {
            if first_line.starts_with("#!") {
                let lower = first_line.to_lowercase();
                if lower.contains("node") || lower.contains("deno") || lower.contains("ts-node") {
                    return "//";
                }
                if lower.contains("lua") {
                    return "--";
                }
                // bash, sh, python, ruby, perl, php, R → "#"
                return "#";
            }
        }
        match path.extension().and_then(|e| e.to_str()) {
            Some("js") | Some("ts") | Some("mjs") | Some("cjs") => "//",
            Some("lua") => "--",
            _ => "#",
        }
    }

    fn extract_annotations(
        content: &str,
        comment_prefix: &str,
    ) -> Result<Option<ScriptAnnotations>, AgentOSError> {
        let mut name: Option<String> = None;
        let mut description = String::new();
        let mut version = "0.1.0".to_string();
        let mut permissions: Vec<String> = vec!["fs.data:r".to_string()];
        let mut risk = "readonly_scoped".to_string();
        let mut timeout_secs: u64 = 30;
        let mut tags: Vec<String> = Vec::new();
        let mut allow_network = false;
        let mut input_hint: Option<String> = None;
        let mut schema: Option<serde_json::Value> = None;

        // Scan only the first 60 lines to avoid reading large scripts entirely.
        for line in content.lines().take(60) {
            let trimmed = line.trim();
            let rest = match trimmed.strip_prefix(comment_prefix) {
                Some(r) => r.trim(),
                None => continue,
            };
            if !rest.starts_with('@') {
                continue;
            }

            if let Some(v) = rest.strip_prefix("@agentos tool:").map(str::trim) {
                name = Some(v.to_string());
            } else if let Some(v) = rest.strip_prefix("@description:").map(str::trim) {
                description = v.to_string();
            } else if let Some(v) = rest.strip_prefix("@version:").map(str::trim) {
                // Reject control characters (ANSI escapes, newlines) and cap length to
                // prevent terminal injection when `agentos script list` renders the version.
                if v.len() <= 64 && v.chars().all(|c| !c.is_control()) {
                    version = v.to_string();
                } else {
                    tracing::warn!(
                        "@version: contains control chars or exceeds 64 bytes — using default"
                    );
                }
            } else if let Some(v) = rest.strip_prefix("@permissions:").map(str::trim) {
                // Merge declared permissions with the default `fs.data:r` rather than
                // replacing it. Scripts almost always need to read their data_dir, and
                // silently stripping the default causes confusing runtime failures.
                let declared = v
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty());
                for p in declared {
                    if !permissions.contains(&p) {
                        permissions.push(p);
                    }
                }
            } else if let Some(v) = rest.strip_prefix("@risk:").map(str::trim) {
                risk = v.to_string();
            } else if let Some(v) = rest.strip_prefix("@timeout:").map(str::trim) {
                // max(1): reject zero-second timeouts that would expire immediately.
                timeout_secs = v
                    .parse::<u64>()
                    .unwrap_or(30)
                    .clamp(1, MAX_SCRIPT_TIMEOUT_SECS);
            } else if let Some(v) = rest.strip_prefix("@tags:").map(str::trim) {
                tags = v
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            } else if let Some(v) = rest.strip_prefix("@network:").map(str::trim) {
                allow_network = v.eq_ignore_ascii_case("true");
            } else if let Some(v) = rest.strip_prefix("@input:").map(str::trim) {
                input_hint = Some(v.to_string());
            } else if let Some(v) = rest.strip_prefix("@schema:").map(str::trim) {
                // Value is compact JSON (one line) generated by the Python SDK.
                // Only accept JSON objects — scalars/arrays are likely annotation
                // mistakes and must not be forwarded to the LLM as tool schema.
                match serde_json::from_str::<serde_json::Value>(v) {
                    Ok(parsed) if parsed.is_object() => schema = Some(parsed),
                    Ok(_) => {
                        tracing::warn!(
                            "@schema: annotation is not a JSON object — falling back to description-only"
                        );
                    }
                    Err(e) => {
                        tracing::warn!(
                            error = %e,
                            "@schema: annotation contains invalid JSON — falling back to description-only"
                        );
                    }
                }
            }
        }

        let name = match name {
            // Whitespace-only or absent annotation — silently treat as "not a script tool".
            Some(n) if !n.is_empty() => n,
            _ => return Ok(None),
        };

        // Validate: kebab-case, no path separators, no dots
        if name.contains('/')
            || name.contains('\\')
            || name.contains('.')
            || !name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        {
            return Err(AgentOSError::SchemaValidation(format!(
                "Script tool name '{}' must be kebab-case (alphanumeric, hyphens, underscores only)",
                name
            )));
        }

        // Derive allow_network from permissions list if not explicitly set
        let allow_network = allow_network
            || permissions
                .iter()
                .any(|p| p.starts_with("network.outbound"));

        // Append input hint to description so the LLM sees it
        let description = match input_hint {
            Some(ref hint) => format!("{} Input: {}", description, hint),
            None => description,
        };

        Ok(Some(ScriptAnnotations {
            name,
            description,
            version,
            permissions,
            risk,
            timeout_secs,
            tags,
            allow_network,
            schema,
        }))
    }
}

// ---------------------------------------------------------------------------
// ScriptTool
// ---------------------------------------------------------------------------

/// An `AgentTool` implementation that executes a user-provided script file.
///
/// The script receives its JSON payload via the `AGENTOS_INPUT` environment
/// variable and must write a JSON object to stdout as its result.
///
/// Execution is sandboxed with `bwrap` (bubblewrap) — the same isolation used
/// by `shell-exec`. Network access is off by default; set `@network: true` or
/// include `network.outbound:x` in `@permissions` to enable it.
pub struct ScriptTool {
    pub(crate) script_path: PathBuf,
    annotations: ScriptAnnotations,
    parsed_permissions: Vec<(String, PermissionOp)>,
}

impl ScriptTool {
    pub fn new(script_path: PathBuf, annotations: ScriptAnnotations) -> Result<Self, AgentOSError> {
        let parsed_permissions = parse_permission_strings(&annotations.permissions)?;
        Ok(Self {
            script_path,
            annotations,
            parsed_permissions,
        })
    }

    pub fn script_path(&self) -> &Path {
        &self.script_path
    }

    pub fn annotations(&self) -> &ScriptAnnotations {
        &self.annotations
    }
}

#[async_trait]
impl AgentTool for ScriptTool {
    fn name(&self) -> &str {
        &self.annotations.name
    }

    fn required_permissions(&self) -> Vec<(String, PermissionOp)> {
        self.parsed_permissions.clone()
    }

    async fn execute(
        &self,
        payload: serde_json::Value,
        context: ToolExecutionContext,
    ) -> Result<serde_json::Value, AgentOSError> {
        let input_json = payload.to_string();
        let data_dir_str = context.data_dir.to_string_lossy().to_string();
        let script_str = self.script_path.to_string_lossy().to_string();
        let timeout = Duration::from_secs(self.annotations.timeout_secs);
        let tool_name = self.annotations.name.clone();

        // bwrap is required — check once and cache the result.
        if !is_bwrap_available().await {
            return Err(AgentOSError::ToolExecutionFailed {
                tool_name,
                reason: "bwrap (bubblewrap) is not installed. Script tools require sandbox \
                         isolation. Install bwrap to enable script tool execution."
                    .into(),
            });
        }

        let mut cmd = Command::new("bwrap");

        // --unshare-all must come first so all subsequent namespace operations
        // (--proc, --dev, --tmpfs, --bind) act inside the new namespaces.
        cmd.arg("--unshare-all");

        // Re-share network only when explicitly requested by the annotation.
        if self.annotations.allow_network {
            cmd.arg("--share-net");
        }

        // Bind standard system directories read-only.
        // Guard each optional path — on UsrMerge distros /bin, /sbin, /lib
        // may not exist as real directories (symlinked to /usr/*).
        cmd.arg("--ro-bind").arg("/usr").arg("/usr");
        for path in ["/bin", "/sbin", "/lib", "/lib64"] {
            if Path::new(path).exists() {
                cmd.arg("--ro-bind").arg(path).arg(path);
            }
        }

        // Bind the script to a fixed path OUTSIDE data_dir so the subsequent
        // writable data_dir bind cannot shadow or override the read-only script mount.
        // Scripts under data_dir/scripts/ would be made writable if we bound data_dir
        // first and then tried to ro-bind a child path — the parent rw-bind shadows it.
        // Using /agentos-script sidesteps that entirely.
        const SCRIPT_SANDBOX_PATH: &str = "/agentos-script";
        cmd.arg("--ro-bind")
            .arg(&script_str)
            .arg(SCRIPT_SANDBOX_PATH)
            // Bind data dir writable — the only location scripts may write.
            .arg("--bind")
            .arg(&data_dir_str)
            .arg(&data_dir_str)
            // Cover sensitive directories with empty tmpfs mounts.
            // /tmp is writable (in-memory tmpfs — scripts may use it freely).
            .arg("--tmpfs")
            .arg("/root")
            .arg("--tmpfs")
            .arg("/etc")
            .arg("--tmpfs")
            .arg("/var")
            .arg("--tmpfs")
            .arg("/home")
            .arg("--tmpfs")
            .arg("/tmp")
            .arg("--dev")
            .arg("/dev")
            .arg("--proc")
            .arg("/proc");

        // When network access is enabled, restore the files DNS resolution needs.
        // /etc was masked with an empty tmpfs above — overlay just the required files.
        // Without these, any HTTPS/DNS call inside the sandbox fails with opaque errors.
        if self.annotations.allow_network {
            for path in [
                "/etc/resolv.conf",
                "/etc/hosts",
                "/etc/ssl/certs",
                "/etc/ca-certificates",
                "/etc/pki",
            ] {
                if Path::new(path).exists() {
                    cmd.arg("--ro-bind").arg(path).arg(path);
                }
            }
        }

        cmd.arg("--chdir")
            .arg(&data_dir_str)
            .arg("--")
            .arg(SCRIPT_SANDBOX_PATH)
            // Clear all inherited env vars — don't leak host secrets into the sandbox.
            // Then re-add only what the script needs. (W8: removed dead pre-clear env block)
            .env_clear()
            .kill_on_drop(true);

        // Minimal environment: PATH for interpreter resolution + AGENTOS_ context vars.
        cmd.env(
            "PATH",
            "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        )
        .env("AGENTOS_INPUT", &input_json)
        .env("AGENTOS_TASK_ID", context.task_id.to_string())
        .env("AGENTOS_AGENT_ID", context.agent_id.to_string())
        .env("AGENTOS_DATA_DIR", &data_dir_str);

        let output = tokio::select! {
            result = tokio::time::timeout(timeout, cmd.output()) => {
                result
                    .map_err(|_| AgentOSError::ToolExecutionFailed {
                        tool_name: tool_name.clone(),
                        reason: format!(
                            "Script timed out after {}s",
                            self.annotations.timeout_secs
                        ),
                    })?
                    .map_err(|e| AgentOSError::ToolExecutionFailed {
                        tool_name: tool_name.clone(),
                        reason: format!("Failed to spawn script: {}", e),
                    })?
            }
            _ = context.cancellation_token.cancelled() => {
                return Err(AgentOSError::ToolExecutionFailed {
                    tool_name,
                    reason: "Tool execution cancelled".into(),
                });
            }
        };

        let stderr = String::from_utf8_lossy(&output.stderr);

        // UTF-8 safe truncation: walk back from the byte limit to a char boundary.
        let truncate = |s: &str, max: usize| -> String {
            if s.len() <= max {
                return s.to_string();
            }
            let mut end = max;
            while !s.is_char_boundary(end) {
                end -= 1;
            }
            s[..end].to_string()
        };

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let reason = if stderr.is_empty() {
                format!("Script exited with code {}", exit_code)
            } else {
                let preview = truncate(stderr.trim(), 500);
                format!("Script exited with code {}: {}", exit_code, preview)
            };
            return Err(AgentOSError::ToolExecutionFailed { tool_name, reason });
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let trimmed = stdout.trim();

        // Log stderr at debug level on success so operators can diagnose scripts
        // that write diagnostics to stderr (the standard convention). (W7 fix)
        let stderr_str = stderr.trim();
        if !stderr_str.is_empty() {
            tracing::debug!(
                tool_name = %tool_name,
                stderr = %stderr_str,
                "Script produced stderr output (exit 0)"
            );
        }

        let mut result = serde_json::from_str::<serde_json::Value>(trimmed).map_err(|e| {
            let preview = truncate(trimmed, 200);
            AgentOSError::ToolExecutionFailed {
                tool_name: tool_name.clone(),
                reason: format!(
                    "Script stdout is not valid JSON: {}. Output was: {:?}",
                    e, preview
                ),
            }
        })?;

        // If stderr is non-empty and result is a JSON object, attach a truncated
        // preview under "_stderr" so agents can see diagnostic output.
        if !stderr_str.is_empty() {
            if let Some(obj) = result.as_object_mut() {
                let preview = truncate(stderr_str, 300);
                obj.insert(
                    "_stderr".to_string(),
                    serde_json::Value::String(preview.to_string()),
                );
            }
        }

        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// ScriptRegistry — tracks path → tool_name for unregistration
// ---------------------------------------------------------------------------

/// Tracks which script path corresponds to which tool name.
/// Used by `ScriptWatcher` to unregister tools when their file is deleted.
#[derive(Default)]
pub struct ScriptRegistry {
    path_to_name: HashMap<PathBuf, String>,
}

impl ScriptRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn record(&mut self, path: PathBuf, name: String) {
        // Evict any existing path that already maps to the same tool name.
        // This prevents ghost entries when a file is renamed but maps to the
        // same @agentos tool: annotation (same name, different path).
        self.path_to_name.retain(|p, n| p == &path || n != &name);
        self.path_to_name.insert(path, name);
    }

    pub fn remove_path(&mut self, path: &Path) -> Option<String> {
        self.path_to_name.remove(path)
    }

    pub fn name_for(&self, path: &Path) -> Option<&str> {
        self.path_to_name.get(path).map(String::as_str)
    }

    /// Iterate over all registered (path, name) pairs.
    pub fn entries(&self) -> impl Iterator<Item = (&PathBuf, &String)> {
        self.path_to_name.iter()
    }
}

// ---------------------------------------------------------------------------
// Permission string parsing
// ---------------------------------------------------------------------------

/// Parse `"resource:ops"` strings into `(resource, PermissionOp)` pairs.
///
/// Examples:
/// - `"fs.data:r"` → `[("fs.data", Read)]`
/// - `"fs.data:rw"` → `[("fs.data", Read), ("fs.data", Write)]`
/// - `"network.outbound:x"` → `[("network.outbound", Execute)]`
pub fn parse_permission_strings(
    perms: &[String],
) -> Result<Vec<(String, PermissionOp)>, AgentOSError> {
    let mut out = Vec::new();
    for perm in perms {
        let (resource, ops_str) = match perm.split_once(':') {
            Some(pair) => pair,
            None => {
                return Err(AgentOSError::SchemaValidation(format!(
                    "Invalid permission string '{}': expected 'resource:ops'",
                    perm
                )))
            }
        };
        for ch in ops_str.chars() {
            let op = match ch {
                'r' => PermissionOp::Read,
                'w' => PermissionOp::Write,
                'x' => PermissionOp::Execute,
                'q' => PermissionOp::Query,
                'o' => PermissionOp::Observe,
                other => {
                    return Err(AgentOSError::SchemaValidation(format!(
                        "Unknown permission op '{}' in '{}'",
                        other, perm
                    )))
                }
            };
            out.push((resource.to_string(), op));
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_script(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn parse_bash_script() {
        let f = write_script(
            r#"#!/bin/bash
# @agentos tool: weather-lookup
# @description: Fetches weather for a city
# @permissions: network.outbound:x
# @risk: readonly_external
# @timeout: 15
# @version: 1.2.0
# @tags: weather, api
echo '{}'
"#,
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert_eq!(ann.name, "weather-lookup");
        assert_eq!(ann.description, "Fetches weather for a city");
        assert_eq!(ann.version, "1.2.0");
        assert_eq!(ann.timeout_secs, 15);
        assert_eq!(ann.risk, "readonly_external");
        assert!(ann.allow_network);
        assert!(ann.tags.contains(&"weather".to_string()));
    }

    #[test]
    fn parse_python_script() {
        let f = write_script(
            r#"#!/usr/bin/env python3
# @agentos tool: process-csv
# @description: Parses a CSV string into rows
# @permissions: fs.data:r
import json, os
print('{}')
"#,
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert_eq!(ann.name, "process-csv");
        assert!(!ann.allow_network);
    }

    #[test]
    fn parse_js_script_double_slash() {
        let f = write_script(
            r#"#!/usr/bin/env node
// @agentos tool: fetch-api
// @description: Fetches JSON from an API
// @permissions: network.outbound:x
console.log('{}');
"#,
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert_eq!(ann.name, "fetch-api");
        assert!(ann.allow_network);
    }

    #[test]
    fn parse_lua_script_double_dash() {
        let f = write_script(
            r#"#!/usr/bin/env lua
-- @agentos tool: compute-hash
-- @description: Computes a hash
print('{}')
"#,
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert_eq!(ann.name, "compute-hash");
    }

    #[test]
    fn parse_no_annotation_returns_none() {
        let f = write_script("#!/bin/bash\necho hello\n");
        let result = ScriptParser::parse(f.path()).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn parse_invalid_name_returns_err() {
        let f = write_script("#!/bin/bash\n# @agentos tool: ../evil\necho '{}'\n");
        let result = ScriptParser::parse(f.path());
        assert!(result.is_err());
    }

    #[test]
    fn parse_network_from_permissions() {
        let f = write_script(
            "#!/bin/bash\n# @agentos tool: my-tool\n# @permissions: network.outbound:x\necho '{}'\n",
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert!(ann.allow_network);
    }

    #[test]
    fn parse_permission_strings_rw() {
        let perms = vec!["fs.data:rw".to_string(), "network.outbound:x".to_string()];
        let parsed = parse_permission_strings(&perms).unwrap();
        assert!(parsed.contains(&("fs.data".to_string(), PermissionOp::Read)));
        assert!(parsed.contains(&("fs.data".to_string(), PermissionOp::Write)));
        assert!(parsed.contains(&("network.outbound".to_string(), PermissionOp::Execute)));
    }

    #[test]
    fn parse_permission_invalid_format() {
        let perms = vec!["no-colon".to_string()];
        assert!(parse_permission_strings(&perms).is_err());
    }

    #[test]
    fn script_registry_roundtrip() {
        let mut reg = ScriptRegistry::new();
        let path = PathBuf::from("/data/scripts/my-tool.sh");
        reg.record(path.clone(), "my-tool".to_string());
        assert_eq!(reg.name_for(&path), Some("my-tool"));
        let name = reg.remove_path(&path);
        assert_eq!(name, Some("my-tool".to_string()));
        assert!(reg.name_for(&path).is_none());
    }

    /// Renaming the source file (different path, same annotation name) should not
    /// leave ghost entries — only the new path should remain in the registry.
    #[test]
    fn script_registry_rename_same_name() {
        let mut reg = ScriptRegistry::new();
        let old_path = PathBuf::from("/scripts/tool-v1.sh");
        let new_path = PathBuf::from("/scripts/tool-v2.sh");

        reg.record(old_path.clone(), "my-tool".to_string());
        assert_eq!(reg.name_for(&old_path), Some("my-tool"));

        // "Rename" — same annotation name, different path.
        reg.record(new_path.clone(), "my-tool".to_string());

        // Old path must be evicted; new path must map to the name.
        assert!(
            reg.name_for(&old_path).is_none(),
            "old path should be evicted"
        );
        assert_eq!(reg.name_for(&new_path), Some("my-tool"));

        // Entry count is 1, not 2.
        assert_eq!(reg.entries().count(), 1);
    }

    /// Editing the annotation name in-place (same path, different name) should
    /// be reflected correctly in the registry after a second record() call.
    #[test]
    fn script_registry_annotation_name_change() {
        let mut reg = ScriptRegistry::new();
        let path = PathBuf::from("/scripts/tool.sh");

        reg.record(path.clone(), "old-name".to_string());
        assert_eq!(reg.name_for(&path), Some("old-name"));

        // Simulate editing @agentos tool: to a new name and re-registering.
        reg.record(path.clone(), "new-name".to_string());

        // The new name is mapped, the old entry is replaced.
        assert_eq!(reg.name_for(&path), Some("new-name"));
        assert_eq!(reg.entries().count(), 1);
    }

    /// An empty ops string ("fs.data:") should parse to zero permission pairs
    /// for that resource — verifying the silent-skip behaviour is intentional.
    #[test]
    fn parse_permission_strings_empty_ops() {
        let perms = vec!["fs.data:".to_string()];
        // Empty ops: the for-loop over chars() produces nothing → valid but empty output.
        let parsed = parse_permission_strings(&perms).unwrap();
        assert!(
            parsed.is_empty(),
            "empty ops string should produce no permission pairs"
        );
    }

    /// A completely unknown permission op character should return Err.
    #[test]
    fn parse_permission_strings_unknown_op() {
        let perms = vec!["fs.data:z".to_string()];
        assert!(parse_permission_strings(&perms).is_err());
    }

    /// @timeout values above the maximum should be clamped to MAX_SCRIPT_TIMEOUT_SECS.
    #[test]
    fn parse_timeout_clamped() {
        let f =
            write_script("#!/bin/bash\n# @agentos tool: slow-tool\n# @timeout: 99999\necho '{}'\n");
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert_eq!(
            ann.timeout_secs, MAX_SCRIPT_TIMEOUT_SECS,
            "timeout should be clamped to {MAX_SCRIPT_TIMEOUT_SECS}"
        );
    }

    /// @permissions annotation merges with the default fs.data:r rather than
    /// replacing it — so a user who only declares network.outbound:x still gets
    /// fs.data:r in the permission set.
    #[test]
    fn parse_permissions_additive_keeps_default() {
        let f = write_script(
            "#!/bin/bash\n# @agentos tool: net-tool\n# @permissions: network.outbound:x\necho '{}'\n",
        );
        let ann = ScriptParser::parse(f.path()).unwrap().unwrap();
        assert!(
            ann.permissions.contains(&"fs.data:r".to_string()),
            "default fs.data:r should be retained when @permissions is set"
        );
        assert!(
            ann.permissions.contains(&"network.outbound:x".to_string()),
            "declared permission should also be present"
        );
    }
}
